default:
    env: server

    alignments: [100_way, 77_way]

    clades: [mammals, aves, sarcopterygii]

    neutral_model_100way_base_url: https://hgdownload.cse.ucsc.edu/goldenpath/hg38/phastCons100way
    neutral_model_100way_file_name: hg38.phastCons100way.mod
    neutral_model_100way_md5_file_name: md5sum.txt

    neutral_model_77way_base_url: https://hgdownload.soe.ucsc.edu/goldenPath/galGal6/phastCons77way
    neutral_model_77way_file_name: galGal6.phastCons77way.mod
    neutral_model_77way_md5_file_name: md5sum.txt

    filtering_100way_mammals: ['hg38', 'otoGar3', 'rheMac3', 'mm10', 'oryCun2', 'ochPri3', 'susScr3', 'turTru2', 'bosTau8', 'felCat8', 'myoLuc2', 'loxAfr3', 'echTel2', 'dasNov3', 'monDom5', 'macEug2', 'ornAna1']
    filtering_100way_sarcopterygii: ['hg38', 'allMis1', 'cheMyd1', 'chrPic2', 'pelSin1', 'apaSpi1', 'anoCar2', 'xenTro7', 'latCha1']
    filtering_77way_aves: ['galGal6', 'cotJap2', 'melGal5', 'tytAlb1', 'bucRhi1', 'anaPla1', 'apaVit1', 'calAnn1', 'cucCan1', 'chaVoc2', 'fulGla1', 'tauEry1', 'opiHoa1', 'phoRub1', 'colLiv1', 'lepDis1', 'merNub1', 'pelCri1', 'phaCar1', 'phaLep1', 'pteGut1', 'nipNip1', 'egrGar1', 'pygAde1', 'aptFor1', 'carCri1', 'mesUni1', 'eurHel1', 'balPav1', 'chlUnd1', 'falChe1', 'falPer1', 'aquChr2', 'halAlb1', 'halLeu1', 'corBra1', 'corCor1', 'acaChl1', 'ficAlb2', 'serCan1', 'zonAlb1', 'geoFor1', 'taeGut2', 'pseHum1', 'gavSte1', 'capCar1', 'melUnd1', 'amaVit1', 'araMac1', 'colStr1', 'picPub1', 'strCam1', 'tinGut2']
    filtering_77way_sarcopterygii: ['galGal6', 'allMis1', 'cheMyd1', 'chrPic2', 'pelSin1', 'apaSpi1', 'anoCar2', 'xenTro9']

# this is env value, possible values {local_pc, server, aws, ...}
local_pc:
# TODO

server:
    inherits: default
    data_preparation:
        alignments: !expr alignments
        source:
            100_way:
                base_url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/multiz100way/maf
                file_name_pattern:  "chr{chr}.maf.gz"
                md5_file_name: md5sum.txt
                chrs: !expr seq(1, 22)
            77_way:
                base_url: https://hgdownload.soe.ucsc.edu/goldenPath/galGal6/multiz77way/maf
                file_name_pattern:  "chr{chr}.maf.gz"
                md5_file_name: md5sum.txt
                chrs: !expr seq(1, 33)
        storage:
            local:
                base_path: /u03/pbeati/2024/lucia/acc_regions_mammals_aves
            aws:
                base_url:
    conservation:
        alignments: !expr alignments
        clades: !expr clades
        neutral_model:
            100_way:
                base_url: !expr neutral_model_100way_base_url
                file_name: !expr neutral_model_100way_file_name
                md5_file_name: !expr neutral_model_100way_md5_file_name
            77_way:
                base_url: !expr neutral_model_77way_base_url
                file_name: !expr neutral_model_77way_file_name
                md5_file_name: !expr neutral_model_77way_md5_file_name
        filtering:
            100_way:
                mammals: !expr filtering_100way_mammals
                sarcopterygii: !expr filtering_100way_sarcopterygii
            77_way:
                aves: !expr filtering_77way_aves
                sarcopterygii: !expr filtering_77way_sarcopterygii
    acceleration:
        alignments: !expr alignments
        clades: !expr clades
        neutral_model:
            100_way:
                base_url: !expr neutral_model_100way_base_url
                file_name: !expr neutral_model_100way_file_name
                md5_file_name: !expr neutral_model_100way_md5_file_name
            77_way:
                base_url: !expr neutral_model_77way_base_url
                file_name: !expr neutral_model_77way_file_name
                md5_file_name: !expr neutral_model_77way_md5_file_name
        filtering:
            100_way:
                mammals: !expr filtering_100way_mammals
            77_way:
                aves: !expr filtering_77way_aves
    custom_filtering:
        alignments: !expr alignments
        clades: !expr clades
        filtering:
            100_way:
                shift_specie: 'ornAna1'
                mammals:
                    species: !expr filtering_100way_mammals
                    consensus_threshold: 0.8
                sarcopterygii:
                    species: !expr filtering_100way_sarcopterygii
                    consensus_threshold: 0.6
            77_way:
                shift_specie: 'tinGut2'
                aves:
                    species: !expr filtering_77way_aves
                    consensus_threshold: 0.8
                sarcopterygii:
                    species: !expr filtering_77way_sarcopterygii
                    consensus_threshold: 0.6

# https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
# https://spacelift.io/blog/yaml

# vars:
#    service1:
#        config: &service_config
#            env: prod
#            retries: 3
#            version: 4.8
#    service2:
#        config:
#            <<: *service_config
#            version: 5
#    service3:
#        config:
#            <<: *service_config
#            version: 4.2
